### ISSUE TITLE
dialog to select steps shows wrong results

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#10]
### Description

When I want to add a step and start to type some letters wrong (too many) results are displayed.

### Steps to reproduce

1. select "Add step" /right click on canvas) or press CTRL-I
2. type in "data" or "folder"

### Expected behavior

Only steps are shown that contain the word data

### Actual behavior

Other steps are shown as well. E.g. if typing in "folder" the "deserialize" step is shown. or typing in "data" shows the "Distinct" step.
![grafik](https://user-images.githubusercontent.com/6207140/89730640-dd131980-da40-11ea-9777-d6e701ce0e4e.png)

### Environment

* Tweakstreet Version 1.4.1
* Fedora 32, Gnome

**Comment by slawo-ch** [comment]
Fixed in 1.5.0

![Screenshot 2020-08-14 at 22 16 41](https://user-images.githubusercontent.com/6863403/90289289-dab72200-de7b-11ea-8fef-f23ca6ce53a1.png)

**Comment by uwegeercken** [comment]
cool.
