### ISSUE TITLE
Context help for Step with F1

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#11]
### Problem description

When double-clicking a step and then pressing _F1_ the help page at _dist/docs/index.html_ is opened. When double-clicking a step and then clicking on on the drop-down next to the steps name and selecting _Help_ the help for the step is displayed at _dist/docs/docs/steps/reference/map/<step>/index.html_

### Preferred solution

Change the behaviour that when the configuration page of the step is open and _F1_ is pressed, the help for that particular step is displayed. So pressing _F1_ on the step configuration page and selecting _Help" from the drop down should result in the same page.

**Comment by slawo-ch** [comment]
implemented in 1.5.1
