### ISSUE TITLE
Color of selected step in list of steps popup

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#12]
### Problem description

When opening the dialog to add a step and typing some letters, a match is displayed in the list. The backgroud color is grey and the foreground color of the selection is a light blue. The light blue is partly very hard to see.

### Preferred solution

Change the color so it is better visible. Or make the color selectable in the main configuration. Alternatively one could maybe use a different way of showing the selected entry - e.g. by an arrow or inverting text or something similar.

**Comment by slawo-ch** [comment]
color has been adjusted in 1.5.0

![Screenshot 2020-08-14 at 22 15 53](https://user-images.githubusercontent.com/6863403/90289239-bf4c1700-de7b-11ea-98e6-21cb675c75bf.png)
