### ISSUE TITLE
Zoom in shortcut wrong

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#17]
### Description

The shortcut to zoom in to the canvas is supposed to be: Strg + = 

But actually it is mapped to Strg + + on the keyboard.

Change the label to show Strg + +

**Comment by slawo-ch** [comment]
I wish there was an easy fix.
See: https://github.com/electron/electron/issues/15496

**Comment by uwegeercken** [comment]
ok. we wait for a fix then

**Comment by slawo-ch** [comment]
Fix in electron is done and will be applied in TS 1.17.5
