### ISSUE TITLE
Enhance display of shortcuts on main screen

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#18]
### Problem description

The shortcut to the command palette on the main screen right after tweakstreet is started is wrapped to the next line. this doe not look well.

![grafik](https://user-images.githubusercontent.com/6207140/90378935-4f57af80-e07a-11ea-89b5-c31cfe76b404.png)

### Preferred solution

make the container where the shortcuts are displayed wider, so that longer text does not wrap to the next line.

**Comment by slawo-ch** [comment]
fixed in 1.5.1
