### ISSUE TITLE
Allow disabling of steps

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#24]
### Problem description

Sometimes during development one copies steps onto the canvas, but these are not (yet) part of the flow. Or different variations of how to solve an issue are put on the canvas. Then, when the flow is run, these steps should not be included in the run. 

The solution of cutting the steps from the flow and placing them in a temporary flow is cumbersome and inefficient and thus not a good option.

### Preferred solution

Add functionality to "disable" a step. A disabled step will not be part of a run. Data arriving at a disabled step will stop there. A disabled step will generate no output. Disabled steps should have a visual indicator so they can be differenciated from the others.

**Comment by slawo-ch** [comment]
The intended utility seems to be to have several experimental, and possibly misconfigured, steps laying on the canvas for convenience. This is best done in a separate scrap-flow and copy and pasted from there. 

The semantics of having 'disabled' and misconfigured steps be part of a flow are difficult to model, and has plenty of edge cases. A step that behaves like a black hole still has static behavior - for example lineage information about fields coming in and going out. And follow up steps - like the 'Rows Exist' take advantage of that information even if there are no rows passing through. 

If the intended purpose is to prevent a step from passing on rows to other steps, this can already be achieved by disabling its outgoing hops.

If the intended purpose is to prevent a step from performing a potentially destructive operation - like deleting files - the step in question should offer a test mode - like the delete files step does. If that is the case please open a case for the step in question.

Closing this one out as the complexity of the feature seems to greatly outweigh the benefits.
