### ISSUE TITLE
little inaccurancy in documentation

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#26]
### Description
In the documentation for the File Info step, under the "Results" section the dict attributes are listed. The last
entry for ctime - the second row - is not properly displayed.

![grafik](https://user-images.githubusercontent.com/6207140/91978318-2dba2180-ed24-11ea-86e5-0c076891f7d6.png)

### Steps to reproduce

n/a

### Expected behavior

The text for the attribute should properly be displayed for the second line.

**Comment by slawo-ch** [comment]
Good catch! Will be fixed in next release.

**Comment by uwegeercken** [comment]
this one is fixed
