### ISSUE TITLE
Typo in tweakflow documentation for data type=Any

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#34]
### Description

Following sentence (the beginning) for the data type = Any does not make sense. Ref: https://twineworks.github.io/tweakflow/reference.html#any

"The any type is a type is not concrete type of its own, but it is used to indicate the possibility of any type being present in the given context."

**Comment by slawo-ch** [comment]
Fixed in Tweakflow 1.3 release
it now reads:


> The any type is not a proper type of its own. It indicates the possibility of any type being present in the given context. It is the default type declaration for variables, parameters and return types unless another type is given.
