### ISSUE TITLE
generator strings does not respect repeat setting

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#40]
### Description

I have configured a generator for strings and defined a minimum and maximum number of repetitions. although a minimum is defined, there are strings generated with less characters.

### Steps to reproduce

- add a generator string field in the random data step
- set the pattern to: [0-9]{4,4}
- run the flow

### Expected behavior

Expected to get only strings of 4 characters length

### Actual behavior

I get strings of less than 4 letters.

### Environment

* Tweakstreet Version 1.91
* Operating system and version: Fedora 32, 64bit, 16Gb RAM, Gnome (Wayland)

**Comment by slawo-ch** [comment]
Hi Uwe,

can you share a flow that demonstrates the problem?

I've tried reproducing it like this:
![Screenshot 2020-10-12 at 11 08 02](https://user-images.githubusercontent.com/6863403/95727985-37b43600-0c7b-11eb-81dc-3cbb347fab7b.png)

And I am always getting results as expected:
![Screenshot 2020-10-12 at 11 08 45](https://user-images.githubusercontent.com/6863403/95728045-50bce700-0c7b-11eb-8e49-651234bd54b0.png)
