### ISSUE TITLE
Block Until Finished step in wrong documentation category

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#41]
### Description

The Block Until Finished step is listed under the category "Database" in the documentation.

### Steps to reproduce

look here: https://docs.tweakstreet.io/docs/steps/reference/buffer/blockuntilfinished/index.html

### Expected behavior

Move the documentation to the category "Utility"

**Comment by slawo-ch** [comment]
Resolved in 1.11.1
