### ISSUE TITLE
Kafka Producer stops with error on more than one header 

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#42]
### Description

When sending a message using the Kafka producer and under "Message Details" a single header is defined, the message is sent without issues.

But when defining another header like this:

![grafik](https://user-images.githubusercontent.com/6207140/104911703-903a5400-598b-11eb-9437-042f802fefd0.png)

The flow throws an error on run:

ERROR:
  code: java.lang.NullPointerException
  message: Null header keys are not permitted
TRACE:
  java.base/java.util.Objects.requireNonNull(Unknown Source)
  org.apache.kafka.common.header.internals.RecordHeader.<init>(RecordHeader.java:33)
  org.apache.kafka.common.header.internals.RecordHeaders.add(RecordHeaders.java:73)
  com.twineworks.tweakstreet.library.steps.map.kafkaproducer.KafkaProducer.addHeaders(KafkaProducer.java:242)
  com.twineworks.tweakstreet.library.steps.map.kafkaproducer.KafkaProducer.work(KafkaProducer.java:275)
  com.twineworks.tweakstreet.engine.exec.data.MapShell.work(MapShell.java:356)
  com.twineworks.tweakstreet.engine.exec.data.ExecutableDataFlow$DataFlowWorker.run(ExecutableDataFlow.java:829)

### Steps to reproduce

1. Define one row (header) in the Kafka Producer step
2. Run the flow and check that it works ok
3. Add another header row in the step
4. Run the flow and receive the error message

### Expected behavior

Multiple headers should correctly be sent with the Kafka message

### Actual behavior

An error occurs.

### Environment

* Tweakstreet Version 1.14.1
* Operating system and version: Fedora 33

**Comment by slawo-ch** [comment]
Fixed in 1.14.2
