### ISSUE TITLE
Documentation: "find" twice in index

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#45]
### Description

there is a function data.find and a function data.find_index. In the documentation - in the index on the left - both are listed as "find"

### Steps to reproduce

1. call help from Tweakstreet
2. go to Expressions >> Computations >> data
3. see that "find" is listed twice

### Expected behavior

The first entry should be "find index"

### Actual behavior

Both values are listed as "find"

### Environment

* Tweakstreet Version 1.14.1
* Operating system and version: Fedora 33

**Comment by slawo-ch** [comment]
Fixed in 1.14.2
