### ISSUE TITLE
Run dialog does not save settings

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#47]
### Description

When changes are made to the tracking, logging or the memory settings, these are only conserved as long as the control flow or data flow is open in Tweakstreet. When the flow is closed, the settings are lost.

### Steps to reproduce

1. Open a control flow or data flow and and some steps
2. open the run dialog and make changes to the settings
3. run the flow
4. open the run dialog - the changes made under 2. are still present
5. close the flow and re-open it - all changes are lost

### Expected behavior

The settings should be conserved, so that next time the flow is run with the last settings.

### Actual behavior

Changes are lost.

### Environment

* Tweakstreet Version 1.14.2
* Operating system and version: Fedora 33, Gnome desktop

**Comment by slawo-ch** [comment]
This is by design. 
Run settings are not supposed to be saved with the file. As long as the file is open - tweakstreet remembers how it was run as a convenience during development.
