### ISSUE TITLE
Indicate where a variable or field is created

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#5]
### Problem description

Fields can be created in various places. The developer/user needs to efficiently find out where the origin of a field is.

### Preferred solution

Indicate the origin of a field when hovering over the hop between two steps.

**Comment by uwegeercken** [comment]
see also issue: Header line of hop tooltip styling needs improvement #2

**Comment by slawo-ch** [comment]
resolved as part of v1.4.1

**Comment by uwegeercken** [comment]
very good. thanks Slawo
