### ISSUE TITLE
Folder for selfmade jar files

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#52]
### Problem description

If someone creates a jar file with classes and functions, the jar has to be put in the Tweakstreet installation bin/lib folder. The problem is that with a new release this file would disappear or respectively has to be copied again to the new release.

### Preferred solution

Allow jar files to be put into a folder under the TWEAKSTREET_HOME folder. E.g. in a folder named "lib". On start the folder shall be scanned to load relevant files.

**Comment by slawo-ch** [comment]
Added in 1.16.1: Jars in `TWEAKSTREET_HOME/lib` are put into the classpath
