### ISSUE TITLE
Excel Input step runtime error

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#53]
### Description

When an empty Excel sheet is selected and the "Header Line" checkbox is checked, on an attempt to auto-detect the fields a runtime error occurs.

### Steps to reproduce

1. add Excel Input step to a flow
2. select an Excel file
3. select an empty sheet in the file
4. make sure the "Header Line" checkbox is checked
5. click on "Auto-detect fileds"

### Expected behavior

Nothing should be returned, as the sheet is empty and even though the "Headerline" is checked. No error should be reported. 

### Actual behavior

A runtime error occurs. I assume because a header line was specified to be present, but the sheet is empty.

Error:
Index -1 out of bounds for length 0
INFO: 
  at: unknown
  code: RUNTIME_ERROR
  message: Index -1 out of bounds for length 0
  value: nil
ERROR: 
  code: java.lang.IndexOutOfBoundsException
  message: Index -1 out of bounds for length 0
TRACE: 
  java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
  java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
  java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
  java.base/java.util.Objects.checkIndex(Unknown Source)
  java.base/java.util.ArrayList.get(Unknown Source)
  com.twineworks.tweakstreet.library.steps.input.excelinput.services.DetectExcelLayout.trimTrailingEmptyColumns(DetectExcelLayout.java:311)
  com.twineworks.tweakstreet.library.steps.input.excelinput.services.DetectExcelLayout.handle(DetectExcelLayout.java:288)
  com.twineworks.tweakstreet.library.services.Services.handleRequest(Services.java:79)
  com.twineworks.tweakstreet.library.services.ipc.StdioServiceServer$RequestProcessor.run(StdioServiceServer.java:192)
  java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.base/java.lang.Thread.run(Unknown Source)

### Environment

* Tweakstreet Version 1.15.1
* Operating system and version: Fedora 33

**Comment by slawo-ch** [comment]
Fixed in 1.16.1
