### ISSUE TITLE
support wireless hops in graph

### ISSUE THREAD

**Issue by slawo-ch** [twineworks/tweakstreet-issues#54]
### Problem description

Steps that are connected in certain ways (error handling steps, or cross-to-new-line layouts) produce visually unappealing and sometimes confusing nets of hops. 

### Preferred solution

We should have the ability to mark a gate as 'wireless' which would make all connected hops 'wireless'. Wireless hops are not drawn on the canvas, and can only be accessed by a smaller visual directly at the step.

**Comment by andrestricker** [comment]
Another option would be to mark hops "suppressable", so they can be suppressed on canvas when not needed to be seen and shown with a global setting (show/hide suppressable hops)

**Comment by slawo-ch** [comment]
![2022-01-28 17 29 42](https://user-images.githubusercontent.com/6863403/151584809-03e7737b-ddfc-43af-a483-c937d1220a83.gif)

Feature added to 1.19.7
