### ISSUE TITLE
Clear input after morphing from nil-type

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#55]
### Problem description

When morphing a widget from NIL to a formula, the word "nil" is still in the formula field. 

### Preferred solution

"Nil" should be cleared

Before morphing:
![grafik](https://user-images.githubusercontent.com/54555531/116547836-b0b36c00-a8f3-11eb-9e34-d5cf5979c808.png)

After morphing:
![grafik](https://user-images.githubusercontent.com/54555531/116547902-c6c12c80-a8f3-11eb-8c86-b928b5b474ed.png)

**Comment by andrestricker** [comment]
> be cleared

be selected and focused so that when you start typing, it's cleared

**Comment by slawo-ch** [comment]
released as part of 1.16.2
