### ISSUE TITLE
Pressing "enter" on a steps name field should close the step

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#56]
### Problem description

If you just want to change the name of a step, you change it and press "enter" and nothing happens

### Preferred solution

If a user presses Enter in the steps name field, the name should be changed and the step should be closed

**Comment by slawo-ch** [comment]
The TS UI does not close dialogs when hitting "enter" in general. If you wish to quickly focus the cancel/close buttons of a dialog hit "escape" (that focuses the cancel button) tab to move over to "OK", then enter
