### ISSUE TITLE
Make it clearer in the preview section of a step that the step is still running

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#58]
### Problem description

When you right-click-preview on a time-consuming step, it's hard to tell if the step is still waiting for data of if it doesn't return any. 

You can see the status of the current job in the Job-Pane, provided that the job list is scrolled all the way up. If not, you will not see, if the empty preview pane shows no data because there is none of because the job is still running. 

### Suggested Solution
Auto-scroll the job pane all the way up to be sure that the current job is currently displayed. 
Show the waiting-gif instead of an empty preview pane until either the first dataset has arrived or there is no data.

**Comment by slawo-ch** [comment]
The preview dialog now shows the stage of the previewed step in the header line.

![2021-06-25 12 55 48](https://user-images.githubusercontent.com/6863403/123415061-008d7700-d5b5-11eb-9933-0d59f83d4d61.gif)
