### ISSUE TITLE
Excel Template sheet copied to output sheet

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#59]
### Description

when creating an excel-output based on a excel template, the template sheet gets copied into the target file. Sample attached

[excel_template.zip](https://github.com/twineworks/tweakstreet-issues/files/6741089/excel_template.zip)

**Comment by slawo-ch** [comment]
That works as intended.
If you use a template sheet it gets copied.
You can always write to an 'existing' sheet if you just want to write data to a sheet without copying it.
