### ISSUE TITLE
SQL Input widget with auto-complete

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#60]
### Description

autocomplete suggestions are not removed when the widget is closed while the suggestions are still open

### Steps to reproduce

1. open a SQL Input widget and press control-space in a field to trigger auto complete#
![grafik](https://user-images.githubusercontent.com/54555531/131975157-25722bcf-a4a2-4e9f-a041-eeadb3ff28b8.png)

2. close widget while the autocomplete suggestions are still open by clicking "ok"
![grafik](https://user-images.githubusercontent.com/54555531/131975257-8b7f9f7d-25e8-4874-ae7c-778df71325b0.png)

suggestions stay there. I sould not get rid of them (only restarting tweakstreet removes them).

**Comment by slawo-ch** [comment]
Fixed in 1.18.7
