### ISSUE TITLE
Allow for empty lines in SQL statements

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#61]
### Problem description

Empty lines in SQL Statements currently mean that a new SQL statement starts. That is counter-intuitive and causes errors that are hard to interprete. 

### Preferred solution

Allow for a list of statements in different widgets each allowing for empty lines.

**Comment by slawo-ch** [comment]
implemented in latest release - you can supply  a list of strings in the SQL Script step now, and each string is interpreted as a separate statement, empty lines within each string of the list carry no meaning in that case.
