### ISSUE TITLE
implement "copy entry vars" button in calculator step

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#63]
### Problem description

When you use the calculator, you have to manually copy the entry vars you use to the output vars. That can be a lot of work

### Preferred solution

Implement a button "copy entry vars" to copy all entry vars with the respective reference

my_var_name        entry_vars.my_var_name

**Comment by slawo-ch** [comment]
implemented in calculator step
![2021-10-22 10 05 12](https://user-images.githubusercontent.com/6863403/138417298-3eb224cc-721b-43ce-a13a-94f6c124162b.gif)
