### ISSUE TITLE
Extend the string parser to trim unicode-spaces as well

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#68]
### Problem description

The trim tickbox does not trim unicode whitespaces but only ascii whitespaces

### Preferred solution

Have the trim tickbox remove unicode whitespaces as well

**Comment by andrestricker** [comment]
[unicode_anti_space.zip](https://github.com/twineworks/tweakstreet-issues/files/7433723/unicode_anti_space.zip)

**Comment by andrestricker** [comment]
strings.trim() should behave the same

**Comment by slawo-ch** [comment]
Fixed in 1.19.2
