### ISSUE TITLE
Add funtionality to preview data when designing flows

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#7]
### Problem description

At runtime but also at design time there is the need to preview data in the flow to work efficiently. E.g. CSV files, Excel sheets, database tables - really any data.

### Preferred solution

Add functionality inside the tweekstreet gui to preview data from a given source. Preview should have functionality to limit the number of rows/elements, possibly also which columns shall be displayed, filter rows/elements functionality and inspect objects such as lists or dicts.

**Comment by slawo-ch** [comment]
Data previews are implemented on every step 1.10 on every step - right click and select "Preview..."
