### ISSUE TITLE
Add TWEAKSTREET_HOME to classpath

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#73]
### Problem description

Add TWEAKSTREET_HOME/lib folder to the classpath, so that own developed jar files with additional functionality will be detected on startup of Tweakstreet.

This avoids that the jar files have to be copied when a new TS version will replace an existing one (removing the old version).

**Comment by slawo-ch** [comment]
fixed, will be part of v1.19.7
