### ISSUE TITLE
Show a popup-window when saving of a process fails

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#75]
### Description

When you try to save a flow and that save failed, you just jet a line in the log windows. 

### Expected behavior

Have a warning popup open that the save has failed..

**Comment by slawo-ch** [comment]
![image](https://user-images.githubusercontent.com/6863403/151550713-2618863c-ed80-4d1c-8835-bf3cc10117cf.png)

popup modal appears when failed to save a file, will be part of 1.19.7
