### ISSUE TITLE
Excel Input: Default the Row Limit field type to "Number"

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#76]
### Description#
In the Excel Input step, Processing Tab, the "Row Limit" field does not accept any values because it is of type "NIL" by default.

### Steps to reproduce
see gif 

### Expected behavior
Set a default field type "number" with default value "nil"

![excel_input](https://user-images.githubusercontent.com/54555531/143575874-9ec11295-8ee9-4026-94a3-4d65377525ba.gif)

**Comment by andrestricker** [comment]
The same applies for the CSV Input field

**Comment by slawo-ch** [comment]
fixed, will be part of v1.19.7
