### ISSUE TITLE
QOL: Build an inline group aggregation step

### ISSUE THREAD

**Issue by andrestricker** [twineworks/tweakstreet-issues#77]
### Problem description

In some cases you need the aggregation result for a group as a field in each of the incoming group rows. Currently this can be solved by forking the stream, group aggregate on one side of the stream and then join by group field. 

### Preferred solution

The above should be built into a single step. You can define the group by fields and the aggregation fields but the aggregation fields should be added as new fields to the incoming rows. If no group by fields are specified, TS should aggregate over all records and add the field(s) to all records

**Comment by slawo-ch** [comment]
implemented by new grouping modes in group by step
