### ISSUE TITLE
Add documentation for partitioning and step instances

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#79]
### Problem description

Partitioning can be defined for the hops as well as the number of instances for a step. There is no documentation available for both topics.

### Preferred solution

Add documentation describing the two topics, in which circumstances they are useful, how both play together and any watch-outs.

**Comment by slawo-ch** [comment]
added and online: https://docs.tweakstreet.io/docs/flows/reference/data-flow/index.html#multiple-instances-of-steps
