### ISSUE TITLE
Remove dummy data in steps

### ISSUE THREAD

**Issue by uwegeercken** [twineworks/tweakstreet-issues#9]
### Problem description

Some steps like e.g. the Data Table step contain dummy/example data per default. So when the step is added it contains the dummy data.

### Preferred solution

Remove the dummy data and alternatively add it as examples in the documentation.

**Comment by slawo-ch** [comment]
Dummy records serve a purpose for usability. An entirely empty widget would be harder to understand how to effectively interact with. 

The dummy records are easy to get rid of and it's easy to keep/rename some fields as opposed to creating them from scratch.

For now the dummy data will stay in.
